spring:
  application:
    name: clientes
  datasource:
    url: jdbc:postgresql://localhost:5432/banco_development_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
